"""mini-airline

Revision ID: 7587e59c4ed6
Revises: 
Create Date: 2026-05-14 13:47:34.630897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7587e59c4ed6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=225), nullable=False),
    sa.Column('role', sa.Enum('admin', 'passenger', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('price_per_seat', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('on_time', 'delayed', 'cancelled', 'landed', name='flightstatus'), nullable=False),
    sa.Column('flight_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['plane_id'], ['Planes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_code')
    )
    op.create_table('Passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.Column('seat_no', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['plane_id'], ['Planes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plane_id', 'seat_no')
    )
    op.create_table('Bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnr', sa.String(length=6), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_status', sa.Enum('active', 'cancelled_by_passenger', 'cancelled_by_airline', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['Flights.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['Passengers.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['Seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_id'),
    sa.UniqueConstraint('pnr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bookings')
    op.drop_table('Seats')
    op.drop_table('Passengers')
    op.drop_table('Flights')
    op.drop_table('Users')
    op.drop_table('Planes')
    # ### end Alembic commands ###
